LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)

LOCAL_MODULE_TAGS := optional
LOCAL_MODULE := OOBE
LOCAL_CERTIFICATE := platform
LOCAL_SRC_FILES := Provision.apk
LOCAL_MODULE_CLASS := APPS
LOCAL_PRODUCT_MODULE := true

# 设置目标安装路径
LOCAL_MODULE_PATH := $(TARGET_OUT_SYSTEM_EXT)
LOCAL_MODULE_RELATIVE_PATH := priv-app

include $(BUILD_PREBUILT)